### ISSUE TITLE
IOS target 11.0 to 12.0 for capacitor 3 compatiblity

### ISSUE THREAD

**Issue by RomainMarecat** [tienmanh94hbk/capacitor-exit-app-ios#1]
Hello, 
Could you change the target ios sdk number to 12.0 for capacitor 3 compatibility ?
Thanks

**Comment by tienmanh94hbk** [comment]
> Hello, Could you change the target ios sdk number to 12.0 for capacitor 3 compatibility ? Thanks
@RomainMarecat sorry for my late reply.
Sure, i will update it in the next minor version. Please wait in update 1.1.1. Thanks you !

**Comment by tienmanh94hbk** [comment]
Because the problem has been updated in version 1.1.1 . So issues will be closed
